# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.operating-system }}
    strategy:      
      matrix:
        operating-system: [ubuntu-latest]
        php-version: ['7.3']
        wordpress-version: ['latest']
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    
    env:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress_test
      MYSQL_VERSION: 5.7
          
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: $MYSQL_VERSION
          mysql database: $MYSQL_DATABASE
          mysql root password: $MYSQL_ROOT_PASSWORD
      
      - run: export PATH="$HOME/.config/composer/vendor/bin:$PATH"
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: phpunit:7.5.20
        
      - name: Install WP Tests
        run: bash bin/install-wp-tests.sh $MYSQL_DATABASE root $MYSQL_ROOT_PASSWORD 127.0.0.1 ${{ matrix.wordpress-version }} true

      - name: Wait for MySQL
        run: |
          while ! mysqladmin ping --host=127.0.0.1 --password=$MYSQL_ROOT_PASSWORD --silent; do
            sleep 1
          done

      - name: PHPUnit tests
        run: phpunit
